name: Deploy
on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: |
          terraform --version
          terraform init
          terraform apply --auto-approve
