name: Deploy
on:
  - pull_request
  - push
  - workflow_dispatch
env:
  ROLE_NAME: accountswitchrole

jobs:
  deploy:
    # runs-on: [self-hosted, Windows]
    runs-on: [self-hosted, Linux]
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1 #! for some reason I had to use this action for the terraform steps to work on LINUX
      - uses: hashicorp/setup-terraform@v1
      - name: Get caller id
        run: |
          terraform init
          terraform apply --auto-approve
          aws s3 ls
      # aws sts get-caller-identity
      # arn:aws:iam::645754663793:role/accountswitchrole
      - name: Switch to prod account role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          # arn:aws:iam::645754663793:role/accountswitchrole
          # role-to-assume: ${{ secrets.PROD_ACCOUNT_ROLE }}
          role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          role-duration-seconds: 3600

      - name: Deploy to account
        run: |
          terraform init
          terraform apply --auto-approve
          aws s3 ls
