name: Deploy
on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  deploy:
    runs-on: [self-hosted, Windows]
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1 #! for some reason in had to use this action for the terraform steps to work
      - uses: hashicorp/setup-terraform@v1

      - run: |
          aws --version
          # terraform --version
          # terraform init
          # terraform apply --auto-approve
          # arn:aws:iam::645754663793:role/accountswitchrole
